var annotated_dup =
[
    [ "Drawable", "namespaceDrawable.html", [
      [ "Drawable", "classDrawable_1_1Drawable.html", "classDrawable_1_1Drawable" ],
      [ "FrameRect", "classDrawable_1_1FrameRect.html", "classDrawable_1_1FrameRect" ]
    ] ],
    [ "Hitbox", "namespaceHitbox.html", [
      [ "Hitbox", "classHitbox_1_1Hitbox.html", "classHitbox_1_1Hitbox" ],
      [ "RectHitbox", "classHitbox_1_1RectHitbox.html", "classHitbox_1_1RectHitbox" ]
    ] ],
    [ "SpawnRule", "namespaceSpawnRule.html", [
      [ "EntityType", "classSpawnRule_1_1EntityType.html", "classSpawnRule_1_1EntityType" ],
      [ "Generator", "classSpawnRule_1_1Generator.html", "classSpawnRule_1_1Generator" ]
    ] ],
    [ "ABonus", "classABonus.html", "classABonus" ],
    [ "ABot", "classABot.html", "classABot" ],
    [ "AError", "classAError.html", "classAError" ],
    [ "AlienEmperor", "classAlienEmperor.html", "classAlienEmperor" ],
    [ "Area", "classArea.html", "classArea" ],
    [ "Assets", "classAssets.html", "classAssets" ],
    [ "BigShip", "classBigShip.html", "classBigShip" ],
    [ "Bonus", "classBonus.html", "classBonus" ],
    [ "Buttons", "classButtons.html", "classButtons" ],
    [ "Clickable", "classClickable.html", "classClickable" ],
    [ "ClientInWorld", "classClientInWorld.html", "classClientInWorld" ],
    [ "Clock", "classClock.html", "classClock" ],
    [ "ComponentArray", "classComponentArray.html", "classComponentArray" ],
    [ "Controllable", "classControllable.html", "classControllable" ],
    [ "CreateEntity", "classCreateEntity.html", "classCreateEntity" ],
    [ "Display", "classDisplay.html", "classDisplay" ],
    [ "Drawable", "classDrawable.html", "classDrawable" ],
    [ "Ennemy", "classEnnemy.html", "classEnnemy" ],
    [ "Entity", "classEntity.html", "classEntity" ],
    [ "Error", "classError.html", "classError" ],
    [ "ErrorClientAlreadyPresentInWorld", "classErrorClientAlreadyPresentInWorld.html", "classErrorClientAlreadyPresentInWorld" ],
    [ "ErrorGenerationMap", "classErrorGenerationMap.html", "classErrorGenerationMap" ],
    [ "ErrorKeyAlreadyExistInMap", "classErrorKeyAlreadyExistInMap.html", "classErrorKeyAlreadyExistInMap" ],
    [ "ErrorKeyNotFound", "classErrorKeyNotFound.html", "classErrorKeyNotFound" ],
    [ "ErrorNoObject", "classErrorNoObject.html", "classErrorNoObject" ],
    [ "ErrorPasswordIncorrect", "classErrorPasswordIncorrect.html", "classErrorPasswordIncorrect" ],
    [ "ErrorVector", "classErrorVector.html", "classErrorVector" ],
    [ "ErrorWorldFull", "classErrorWorldFull.html", "classErrorWorldFull" ],
    [ "FastNoiseLite", "classFastNoiseLite.html", "classFastNoiseLite" ],
    [ "Force", "classForce.html", "classForce" ],
    [ "Game", "classGame.html", "classGame" ],
    [ "GenerateWorld", "classGenerateWorld.html", "classGenerateWorld" ],
    [ "GJKAlgorithm", "classGJKAlgorithm.html", "classGJKAlgorithm" ],
    [ "HandlingParameters", "classHandlingParameters.html", "classHandlingParameters" ],
    [ "Hitbox", "classHitbox.html", "classHitbox" ],
    [ "IClickable", "classIClickable.html", "classIClickable" ],
    [ "KamikazeShooter", "classKamikazeShooter.html", "classKamikazeShooter" ],
    [ "LinearShooter", "classLinearShooter.html", "classLinearShooter" ],
    [ "LockedQueue", "classLockedQueue.html", "classLockedQueue" ],
    [ "MainNetwork", "classMainNetwork.html", "classMainNetwork" ],
    [ "Message", "structMessage.html", "structMessage" ],
    [ "MessageHeader", "structMessageHeader.html", "structMessageHeader" ],
    [ "MyClock", "classMyClock.html", "classMyClock" ],
    [ "Network", "classNetwork.html", "classNetwork" ],
    [ "NetworkClient", "classNetworkClient.html", "classNetworkClient" ],
    [ "NetworkFunctions", "classNetworkFunctions.html", "classNetworkFunctions" ],
    [ "NetworkServer", "classNetworkServer.html", "classNetworkServer" ],
    [ "OneUp", "classOneUp.html", "classOneUp" ],
    [ "PlayerAI", "classPlayerAI.html", "classPlayerAI" ],
    [ "Position", "classPosition.html", "classPosition" ],
    [ "Projectile", "classProjectile.html", "classProjectile" ],
    [ "Registry", "classRegistry.html", "classRegistry" ],
    [ "SinusoidalShooter", "classSinusoidalShooter.html", "classSinusoidalShooter" ],
    [ "SpatialDustman", "classSpatialDustman.html", "classSpatialDustman" ],
    [ "SpawnAfterDead", "classSpawnAfterDead.html", "classSpawnAfterDead" ],
    [ "Speed", "classSpeed.html", "classSpeed" ],
    [ "Star", "classStar.html", "classStar" ],
    [ "Systems", "classSystems.html", "classSystems" ],
    [ "TpShooter", "classTpShooter.html", "classTpShooter" ],
    [ "UpgradeForce", "classUpgradeForce.html", "classUpgradeForce" ],
    [ "Vector", "classVector.html", "classVector" ],
    [ "Velocity", "classVelocity.html", "classVelocity" ],
    [ "VirtualKeyBoard", "classVirtualKeyBoard.html", "classVirtualKeyBoard" ],
    [ "Vitality", "classVitality.html", "classVitality" ],
    [ "World", "classWorld.html", "classWorld" ],
    [ "WorldsIndex", "classWorldsIndex.html", "classWorldsIndex" ]
];