var annotated_dup =
[
    [ "Drawable", "namespaceDrawable.html", [
      [ "Drawable", "classDrawable_1_1Drawable.html", "classDrawable_1_1Drawable" ],
      [ "FrameRect", "classDrawable_1_1FrameRect.html", "classDrawable_1_1FrameRect" ]
    ] ],
    [ "SpawnRule", "namespaceSpawnRule.html", [
      [ "EntityType", "classSpawnRule_1_1EntityType.html", "classSpawnRule_1_1EntityType" ],
      [ "Generator", "classSpawnRule_1_1Generator.html", "classSpawnRule_1_1Generator" ]
    ] ],
    [ "ABot", "classABot.html", "classABot" ],
    [ "AError", "classAError.html", "classAError" ],
    [ "AlienEmperor", "classAlienEmperor.html", "classAlienEmperor" ],
    [ "Area", "classArea.html", "classArea" ],
    [ "Assets", "classAssets.html", "classAssets" ],
    [ "BigShip", "classBigShip.html", "classBigShip" ],
    [ "ClientInWorld", "classClientInWorld.html", "classClientInWorld" ],
    [ "Clock", "classClock.html", "classClock" ],
    [ "CommandHandler", "classCommandHandler.html", "classCommandHandler" ],
    [ "ComponentArray", "classComponentArray.html", "classComponentArray" ],
    [ "Controllable", "classControllable.html", "classControllable" ],
    [ "CreateEntity", "classCreateEntity.html", "classCreateEntity" ],
    [ "Drawable", "classDrawable.html", null ],
    [ "Ennemy", "classEnnemy.html", "classEnnemy" ],
    [ "Entity", "classEntity.html", "classEntity" ],
    [ "ErrorClientAlreadyPresentInWorld", "classErrorClientAlreadyPresentInWorld.html", "classErrorClientAlreadyPresentInWorld" ],
    [ "ErrorGenerationMap", "classErrorGenerationMap.html", "classErrorGenerationMap" ],
    [ "ErrorKeyAlreadyExistInMap", "classErrorKeyAlreadyExistInMap.html", "classErrorKeyAlreadyExistInMap" ],
    [ "ErrorKeyNotFound", "classErrorKeyNotFound.html", "classErrorKeyNotFound" ],
    [ "ErrorManager", "classErrorManager.html", "classErrorManager" ],
    [ "ErrorNoObject", "classErrorNoObject.html", "classErrorNoObject" ],
    [ "ErrorPasswordIncorrect", "classErrorPasswordIncorrect.html", "classErrorPasswordIncorrect" ],
    [ "ErrorVector", "classErrorVector.html", "classErrorVector" ],
    [ "ErrorWorldFull", "classErrorWorldFull.html", "classErrorWorldFull" ],
    [ "FastNoiseLite", "classFastNoiseLite.html", "classFastNoiseLite" ],
    [ "Force", "classForce.html", "classForce" ],
    [ "GenerateWorld", "classGenerateWorld.html", "classGenerateWorld" ],
    [ "GJKAlgorithm", "classGJKAlgorithm.html", "classGJKAlgorithm" ],
    [ "Hitbox", "classHitbox.html", "classHitbox" ],
    [ "KamikazeShooter", "classKamikazeShooter.html", "classKamikazeShooter" ],
    [ "LinearShooter", "classLinearShooter.html", "classLinearShooter" ],
    [ "MyClock", "classMyClock.html", "classMyClock" ],
    [ "Position", "classPosition.html", "classPosition" ],
    [ "Projectile", "classProjectile.html", "classProjectile" ],
    [ "Registry", "classRegistry.html", "classRegistry" ],
    [ "SinusoidalShooter", "classSinusoidalShooter.html", "classSinusoidalShooter" ],
    [ "SpatialDustman", "classSpatialDustman.html", "classSpatialDustman" ],
    [ "SpawnAfterDead", "classSpawnAfterDead.html", "classSpawnAfterDead" ],
    [ "Systems", "classSystems.html", "classSystems" ],
    [ "TpShooter", "classTpShooter.html", "classTpShooter" ],
    [ "UDPClient", "classUDPClient.html", "classUDPClient" ],
    [ "UDPServer", "classUDPServer.html", "classUDPServer" ],
    [ "Vector", "classVector.html", "classVector" ],
    [ "Velocity", "classVelocity.html", "classVelocity" ],
    [ "VirtualKeyBoard", "classVirtualKeyBoard.html", "classVirtualKeyBoard" ],
    [ "Vitality", "classVitality.html", "classVitality" ],
    [ "World", "classWorld.html", "classWorld" ],
    [ "WorldsIndex", "classWorldsIndex.html", "classWorldsIndex" ]
];