var hierarchy =
[
    [ "ABot", "classABot.html", [
      [ "AlienEmperor", "classAlienEmperor.html", null ],
      [ "BigShip", "classBigShip.html", null ],
      [ "KamikazeShooter", "classKamikazeShooter.html", null ],
      [ "LinearShooter", "classLinearShooter.html", null ],
      [ "SinusoidalShooter", "classSinusoidalShooter.html", null ],
      [ "SpatialDustman", "classSpatialDustman.html", null ],
      [ "TpShooter", "classTpShooter.html", null ]
    ] ],
    [ "Area", "classArea.html", null ],
    [ "FastNoiseLite::Arguments_must_be_floating_point_values< double >", "structFastNoiseLite_1_1Arguments__must__be__floating__point__values_3_01double_01_4.html", null ],
    [ "FastNoiseLite::Arguments_must_be_floating_point_values< float >", "structFastNoiseLite_1_1Arguments__must__be__floating__point__values_3_01float_01_4.html", null ],
    [ "FastNoiseLite::Arguments_must_be_floating_point_values< long double >", "structFastNoiseLite_1_1Arguments__must__be__floating__point__values_3_01long_01double_01_4.html", null ],
    [ "Assets", "classAssets.html", null ],
    [ "ClientInWorld", "classClientInWorld.html", null ],
    [ "Clock", "classClock.html", null ],
    [ "CommandHandler", "classCommandHandler.html", null ],
    [ "ComponentArray< Component >", "classComponentArray.html", null ],
    [ "Controllable", "classControllable.html", null ],
    [ "CreateEntity", "classCreateEntity.html", null ],
    [ "Drawable", "classDrawable.html", null ],
    [ "Drawable::Drawable", "classDrawable_1_1Drawable.html", null ],
    [ "Ennemy", "classEnnemy.html", null ],
    [ "Entity", "classEntity.html", null ],
    [ "SpawnRule::EntityType", "classSpawnRule_1_1EntityType.html", null ],
    [ "ErrorManager", "classErrorManager.html", null ],
    [ "std::exception", null, [
      [ "AError", "classAError.html", [
        [ "ErrorClientAlreadyPresentInWorld", "classErrorClientAlreadyPresentInWorld.html", null ],
        [ "ErrorGenerationMap", "classErrorGenerationMap.html", null ],
        [ "ErrorKeyAlreadyExistInMap", "classErrorKeyAlreadyExistInMap.html", null ],
        [ "ErrorKeyNotFound", "classErrorKeyNotFound.html", null ],
        [ "ErrorNoObject", "classErrorNoObject.html", null ],
        [ "ErrorPasswordIncorrect", "classErrorPasswordIncorrect.html", null ],
        [ "ErrorVector", "classErrorVector.html", null ],
        [ "ErrorWorldFull", "classErrorWorldFull.html", null ]
      ] ],
      [ "UDPClient::ClientError", "classUDPClient_1_1ClientError.html", null ],
      [ "UDPServer::Error", "classUDPServer_1_1Error.html", null ]
    ] ],
    [ "FastNoiseLite", "classFastNoiseLite.html", null ],
    [ "Force", "classForce.html", null ],
    [ "Drawable::FrameRect", "classDrawable_1_1FrameRect.html", null ],
    [ "GenerateWorld", "classGenerateWorld.html", null ],
    [ "SpawnRule::Generator", "classSpawnRule_1_1Generator.html", null ],
    [ "GJKAlgorithm", "classGJKAlgorithm.html", null ],
    [ "Hitbox", "classHitbox.html", null ],
    [ "MyClock", "classMyClock.html", null ],
    [ "Position", "classPosition.html", null ],
    [ "Projectile", "classProjectile.html", null ],
    [ "Registry", "classRegistry.html", null ],
    [ "SpawnAfterDead", "classSpawnAfterDead.html", null ],
    [ "Systems", "classSystems.html", null ],
    [ "UDPClient", "classUDPClient.html", null ],
    [ "UDPServer", "classUDPServer.html", null ],
    [ "Vector< T, N >", "classVector.html", null ],
    [ "Velocity", "classVelocity.html", null ],
    [ "VirtualKeyBoard", "classVirtualKeyBoard.html", null ],
    [ "Vitality", "classVitality.html", null ],
    [ "World", "classWorld.html", null ],
    [ "WorldsIndex", "classWorldsIndex.html", null ]
];