name: Deploy Doxygen Documentation

on:
  push:
    branches:
      - main  # Adjust to your default branch

jobs:
  generate-docs:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Doxygen
      run: |
        sudo apt-get update
        sudo apt-get install -y doxygen graphviz  # Install Doxygen and Graphviz

    - name: Generate Doxygen documentation
      run: doxygen Doxyfile  # Replace with your Doxyfile name if different

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GH_TOKEN }}  # Use the secret you created
        publish_dir: ./html  # Adjust to your Doxygen output directory (default: ./html)
